### ISSUE TITLE
`IS_BROWSER` from ember-stdlib/utils/is-browser

### ISSUE THREAD

**Issue by pete-the-pete** [scalvert/ember-bpr-lint#15]
A new deprecation:

`DEPRECATION: Using 'environment.isBrowser()' is deprecated. Please 'import IS_BROWSER from ember-stdlib/utils/is-browser' instead.`

is incompatible with the `No Unguarded Global References` rule.

**Comment by scalvert** [comment]
This repo has been pulled internal. Closing this in favor of that.
