### ISSUE TITLE
environment check doesn't handle short circuit logic

### ISSUE THREAD

**Issue by cclo7** [scalvert/ember-bpr-lint#6]
Currently the lint expects all global browser object like "window" to be wrapped in an if (environment.isBrowser()) condition. It would be great if the lint can handle the case that there is an environment check before the global object reference and not throw an error in that case.

The rational is that sometimes developer may wish to use such short circuit logic to reduce nesting in the code.

For example, ideally this should not throw an error.

```
if (!environment.isBrowser()) {
  return;
}

window.sessionStorage.getItem(...);
```

**Comment by scalvert** [comment]
Additionally, it doesn't handle ternary operators that have an `environment.isBrowser()` check.

**Comment by scalvert** [comment]
Thanks for reporting, @cclo7! I'll try to have a fix ASAP

**Comment by nickiaconis** [comment]
Hey @scalvert, it's been a while; any update on this? I'm bumping into it too.

**Comment by scalvert** [comment]
Sorry, @cclo7. I haven't been able to get to this, but welcome pull requests!

**Comment by scalvert** [comment]
This repo has been pulled internal. This issue is fixed in that repo and should be used in favor of this.
